myproject/urls.py
from django.conf.urls import url
from django.contrib import admin

from boards import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^base/$', views.base, name='base'),
    url(r'^boards/(?P<pk>\d+)/$', views.board_topics, name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    url(r'^admin/', admin.site.urls),
]

boards/models.py
from django.db import models
from django.contrib.auth.models import User


class Board(models.Model):
	name = models.CharField(max_length=30, unique=True)
	description = models.CharField(max_length=100)

	def __str__(self):
		return self.name


class Topic(models.Model):
	"""docstring for Topic"""
	subject = models.CharField(max_length=255)
	last_updated = models.DateTimeField(auto_now_add=True)
	board = models.ForeignKey(Board, related_name='topics')
	starter = models.ForeignKey(User, related_name='topics')


class Post(models.Model):
	"""docstring for Post"""
	message = models.TextField(max_length=4000)
	topic = models.ForeignKey(Topic, related_name='posts')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(null=True)
	created_by = models.ForeignKey(User, related_name='posts')
	updated_by = models.ForeignKey(User, null=True, related_name='+')

boards/forms.py
from django import forms
from .models import Topic


class NewTopicForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': 'What is on your mind?'}
        ),
        max_length=4000,
        help_text='The max length of the text is 4000.'
    )

    class Meta:
        model = Topic
        fields = ['subject', 'message']

boards/views.py
from django.shortcuts import \
	render, HttpResponse, redirect, \
	get_object_or_404, Http404
from django.contrib.auth.models import User

# Create your views here.

from .models import Board, Topic, Post
from .forms import NewTopicForm


def home(request):
	boards = Board.objects.all()
	return render(request, 'home.html', {'boards': boards})


def base(request):
	return render(request, 'base.html')


def board_topics(request, pk):
	# board = Board.objects.get(pk=pk)

	try:
		board = Board.objects.get(pk=pk)
	except Board.DoesNotExist:
		raise Http404

	# board = get_object_or_404(Board, pk=pk)
	return render(request, 'topics.html', {'board': board})


def new_topic(request, pk):
	board = get_object_or_404(Board, pk=pk)
	user = User.objects.first()

	if request.method == 'POST':
		form = NewTopicForm(request.POST)
		if form.is_valid():
			topic = form.save(commit=False)
			topic.board = board
			topic.starter = user
			topic.save()
			post = Post.objects.create(
				message=form.cleaned_data.get('message'),
				topic=topic,
				created_by=user,
			)
			return redirect('board_topics', pk=pk)
	else:
		form = NewTopicForm()

	return render(request, 'new_topic.html', {'board': board, 'form': form})

templates/base.html
{% load static %}<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Django Boards{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
    </div>
</nav>

<div class="container">
    <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
    </ol>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th>Board</th>
            <th>Posts</th>
            <th>Topics</th>
            <th>Last Post</th>
        </tr>
        </thead>
        <tbody>
        {% for board in boards %}
            <tr>
                <td>
                    <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
                    <small class="text-muted d-block">{{ board.description }}</small>
                </td>
                <td class="align-middle">0</td>
                <td class="align-middle">0</td>
                <td></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/includes/form.html
{% load widget_tweaks %}

{% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}

                {% if form.is_bound %}
                    <!-- 提交无效数值页面 -->
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}

                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}

                    {% else %}
                        <!-- 提交有效数值页面 -->
                        {% render_field field class="form-control is-valid" %}
                    {% endif %}

                {% else %}
                    <!-- 初始状态页面 -->
                    {% render_field field class="form-control" %}
                {% endif %}


                <!-- 显示帮助信息 -->
                {% if field.help_text %}
                    <small class="form-text text-muted">
                        {{ field.help_text }}
                    </small>
                {% endif %}
            </div>
        {% endfor %}

templates/new_topic.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href={% url 'home' %}>Boards</a></li>
    <li class="breadcrumb-item"><a href={% url 'board_topics' board.pk %}>{{ board.name }}</a></li>
    <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
    <!-- HTML form -->
    {#    <form method="post">#}
    {#        {% csrf_token %}#}
    {#        <div class="form-group">#}
    {#            <label for="id_subject">Subject</label>#}
    {#            <input type="text" class="form-control" id="id_subject" name="subject">#}
    {#        </div>#}
    {#        <div class="form-group">#}
    {#            <label for="id_message">Message</label>#}
    {#            <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>#}
    {#        </div>#}
    {#        <button type="submit" class="btn btn-success">Post</button>#}
    {#    </form>#}


    <!-- ModelForm v1 -->
    {#    <form method="post" novalidate>#}
    {#        {% csrf_token %}#}
    {#        {{ form.as_p }}#}
    {#        <button type="submit" class="btn btn-success">Post</button>#}
    {#    </form>#}

    <!-- ModelForm v2 -->
    <form method="post" novalidate>
        {% csrf_token %}

        {% include 'includes/form.html' %}

        <button type="submit" class="btn btn-success">Post</button>
    </form>

{% endblock %}

templates/topics.html
{% extends 'base.html' %}

{% block title %}
    {{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href={% url 'home' %}>Boards</a></li>
    <li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block content %}
    <div class="mb-4">
        <a href="{% url 'new_topic' board.pk %}" class="btn btn-primary">New topic</a>
    </div>

    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th>Topic</th>
            <th>Starter</th>
            <th>Replies</th>
            <th>Views</th>
            <th>Last Update</th>
        </tr>
        </thead>
        <tbody>
        {% for topic in board.topics.all %}
            <tr>
                <td>{{ topic.subject }}</td>
                <td>{{ topic.starter.username }}</td>
                <td>0</td>
                <td>0</td>
                <td>{{ topic.last_updated }}</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}